Adding missing include DispatchRaysItem.h in CommandList header, which causes Mac/iOS to fail to compile (#10636)
Fix the following compilation issue on Mac and iOS.

````
/Users/lybuilder/workspace/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp:207:32: error: no viable conversion from 'const RHI::DispatchRaysItem' to 'const AZ::RHI::SubmitItem'
            ValidateSubmitItem(dispatchRaysItem);
````

Signed-off-by: moraaar <moraaar@amazon.com>